"""handles embedding of texts using sentence embeddings"""

from typing import List
from numpy.typing import NDArray
import numpy as np
from app.models import DocumentChunk
from sentence_transformers import SentenceTransformer
from typing import Union

class Embedder:
    def __init__(self, model_name: str): 
        """Initializes the Embedder with the given model.

        Args:
            model_name (str): SentenceTransformer model name.
        """
        self.model_name = model_name
        self.model = SentenceTransformer(model_name)
        
    def embed_texts(self, texts: List[str]) -> NDArray[np.float32]:
        """Embeds a list of texts into a 2D numpy array of shape (N, dim). Uses sentence embeddings.

        Args:
            texts (List[str]): List of texts to embed.

        Returns:
            NDArray[np.float32]: 2D numpy array of shape (N, dim) corresponding to N embeddings of dimension dim.
        """
        if not texts:
            return np.zeros((0, self.dim), dtype=np.float32)
        
        embeddings = self.model.encode(texts, normalize_embeddings=True, convert_to_numpy=True).astype(np.float32)
        return embeddings

    def embed_chunks(self, chunks: List[DocumentChunk]) -> NDArray[np.float32]:
        """Wrapper that embeds a list of DocumentChunks into a 2D numpy array of shape (N, dim). Uses embed_texts()

        Args:
            chunks (List[DocumentChunk]): List of DocumentChunks to embed.

        Returns:
            NDArray[np.float32]: 2D numpy array of shape (N, dim) corresponding to N embeddings of dimension dim.
        """
        if not isinstance(chunks, list):
            raise ValueError(f"Chunks must be a list but got {type(chunks)}")
        for chunk in chunks:
            if not isinstance(chunk, DocumentChunk):
                raise ValueError(f"Chunk {chunk} is not a DocumentChunk")
        
        texts = [chunk.text for chunk in chunks]
        return self.embed_texts(texts)

    def embed_query(self, query: str) -> NDArray[np.float32]:
        """Embeds a single query into a 2D numpy array of shape (1,dim). Uses embed_texts()

        Args:
            query (str): Single query to embed.

        Returns:
            NDArray[np.float32]: 2D numpy array of shape (1, dim) corresponding to the embedding of the query.
        """
        if not isinstance(query, str):
            raise ValueError(f"Query must be a string but got {type(query)}")
        
        return self.embed_texts([query])
    
    @property
    def dim(self) -> Union[int, None]:
        """Returns the dimension of embeddings generated by the model."""
        return self.model.get_sentence_embedding_dimension()
    
    def get_max_embedding_input_length(self) -> Union[int, None]:
        """Returns maximum input length for embedding model."""
        return self.model.get_max_seq_length()